package ArrayDeque;

public class Queue {
    /*
    ARRAYDEQUE -> ESTA É UMA CLASSE ESPECIAL QUE IMPLEMENTA UMA ESTRUTURA
    DE DADOS DE FILA DE DUAS EXTREMIDADES, ONDE PODE
    INSERIR  E REMOVER ELEMENTOS DE AMBAS AS EXTREMIDADES
    SUPORTA A IMPLEMENTACAO DE UM ARRAY REDIMENSIONAVEL QUE CRESCE AUTOMATICAMENTE
     */

    /*
    PRORITY QUEUE -> NESTA CLASSE, O ELEMENTO E INSERIDO NA PARTE
    DE TRAS DA FILA. ESTA OPERACAO E CHAMADA DE ENFILEIRAMENTO. ESTE
    MESMO ELEMENTO SAI A PARTIR DA FRENTE DA FILA, OPERACAO
    CHAMADA DE DESENFILEIRAMENTO. ESSE PROCEDIMENTO DE ENTRADA E SAIDA
    RECEBE O NOME DE FILA, OU FIFO (FIRST-IN FIRST-OUT), OU
    SEJAM, "PRIMEIRO A ENTRAR, PRIMEIRO A SAIR".
     */
}
